spring:
  application:
    name: LovoMallCSC
  profiles:
    active: dev # 当前项目激活配置环境
---
server:
  port: 8082
spring:
  # 开发环境
  profiles: dev
  # thymeleaf 配置
  thymeleaf:
    cache: false # 禁用模板引擎缓存
    template-resolver-order: 0 # 模板引擎视图解析器优先级，数值越低优先级越高
  # datasource 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动版本 com.mysql.jdbc.Driver 是旧版本驱动
    url: jdbc:mysql://127.0.0.1:3306/lovomall-csc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
# 数据库名统一为 lovoma ll-csc
    password: 123 # 修改为自己数据库密码
    username: root # 修改为自己数据库账号
  # jpa jpa配置
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL数据库方言
    hibernate:
      ddl-auto: update
    database: mysql # 数据库
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  activemq:
    broker-url: nio://192.168.1.222:61608
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
  jms:
    pub-sub-domain: false # true topic false queue
# 日志格式
logging:
  pattern:
    dateformat: MM-dd HH-mm
# MQ消息队列名
queuename:
  # 预存款审核模块消息队列名
  precision:
    receive:
      recharge: RECHARGE_REVIEW_QUEUE
      consume: CONSUME_REVIEW_QUEUE
    result:
      recharge: RECHARGE_REVIEW_RESULT_QUEUE
      consume: CONSUME_REVIEW_RESULT_QUEUE
  # 各模块消息队列名按以上格式书写
  pruchase:
    receive:
      purchasePlan: PURCHASE_REVIEW_QUEUE
    result:
      purchasePlan: PURCHASE_REVIEW_RESULT_QUEUE
  supplier:
    receive:
      sign: supplierSign
    result:
      sign: SUPPLIERSIGN_REVIEW_RESULT_QUEUE